// GitHub standard emoji shortcodes → Unicode characters
// Source: https://github.com/github/gemoji
export const EMOJI_MAP: Record<string, string> = {
  // ─── Smileys & Emotion ───────────────────────────────────────────────────────
  grinning: '😀', smiley: '😃', smile: '😄', grin: '😁', laughing: '😆',
  sweat_smile: '😅', rofl: '🤣', joy: '😂', slightly_smiling_face: '🙂',
  upside_down_face: '🙃', wink: '😉', blush: '😊', innocent: '😇',
  heart_eyes: '😍', kissing_heart: '😘', kissing: '😗', kissing_smiling_eyes: '😙',
  kissing_closed_eyes: '😚', yum: '😋', stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜', stuck_out_tongue_closed_eyes: '😝',
  money_mouth_face: '🤑', hugs: '🤗', thinking: '🤔', zipper_mouth_face: '🤐',
  raised_eyebrow: '🤨', neutral_face: '😐', expressionless: '😑',
  no_mouth: '😶', smirk: '😏', unamused: '😒', roll_eyes: '🙄',
  grimacing: '😬', lying_face: '🤥', relieved: '😌', pensive: '😔',
  sleepy: '😪', drooling_face: '🤤', sleeping: '😴', mask: '😷',
  face_with_thermometer: '🤒', face_with_head_bandage: '🤕',
  nauseated_face: '🤢', sneezing_face: '🤧', hot_face: '🥵', cold_face: '🥶',
  woozy_face: '🥴', dizzy_face: '😵', exploding_head: '🤯',
  cowboy_hat_face: '🤠', partying_face: '🥳', sunglasses: '😎',
  nerd_face: '🤓', monocle_face: '🧐', confused: '😕', worried: '😟',
  slightly_frowning_face: '🙁', frowning_face: '☹️', open_mouth: '😮',
  hushed: '😯', astonished: '😲', flushed: '😳', pleading_face: '🥺',
  anguished: '😧', fearful: '😨', cold_sweat: '😰', disappointed_relieved: '😥',
  cry: '😢', sob: '😭', scream: '😱', confounded: '😖', persevere: '😣',
  disappointed: '😞', sweat: '😓', weary: '😩', tired_face: '😫',
  yawning_face: '🥱', triumph: '😤', rage: '😡', angry: '😠',
  skull: '💀', skull_and_crossbones: '☠️', poop: '💩', clown_face: '🤡',
  japanese_ogre: '👹', japanese_goblin: '👺', ghost: '👻', alien: '👽',
  space_invader: '👾', robot: '🤖', wave: '👋', raised_back_of_hand: '🤚',
  raised_hand: '✋', vulcan_salute: '🖖', ok_hand: '👌', pinched_fingers: '🤌',
  pinching_hand: '🤏', v: '✌️', crossed_fingers: '🤞', love_you_gesture: '🤟',
  metal: '🤘', call_me_hand: '🤙', point_left: '👈', point_right: '👉',
  point_up_2: '👆', middle_finger: '🖕', point_down: '👇', point_up: '☝️',
  '+1': '👍', thumbsup: '👍', '-1': '👎', thumbsdown: '👎', fist: '✊',
  oncoming_fist: '👊', left_facing_fist: '🤛', right_facing_fist: '🤜',
  clap: '👏', raised_hands: '🙌', open_hands: '👐', pray: '🙏',
  handshake: '🤝', writing_hand: '✍️', nail_care: '💅', selfie: '🤳',
  muscle: '💪', leg: '🦵', foot: '🦶', ear: '👂', nose: '👃', eyes: '👀',
  eye: '👁️', tongue: '👅', lips: '👄', brain: '🧠', heart_hands: '🫶',

  // ─── People ──────────────────────────────────────────────────────────────────
  baby: '👶', child: '🧒', boy: '👦', girl: '👧', person: '🧑',
  man: '👨', woman: '👩', older_person: '🧓', older_man: '👴',
  older_woman: '👵', cop: '👮', construction_worker: '👷', guard: '💂',
  detective: '🕵️', nurse: '👩‍⚕️', doctor: '🧑‍⚕️', teacher: '🧑‍🏫',
  farmer: '🧑‍🌾', cook: '🧑‍🍳', scientist: '🧑‍🔬', technologist: '🧑‍💻',
  artist: '🧑‍🎨', pilot: '🧑‍✈️', astronaut: '🧑‍🚀', superhero: '🦸',
  supervillain: '🦹', mage: '🧙', fairy: '🧚', vampire: '🧛',
  merperson: '🧜', elf: '🧝', genie: '🧞', zombie: '🧟', person_gesturing_no: '🙅',
  person_gesturing_ok: '🙆', person_tipping_hand: '💁', person_raising_hand: '🙋',
  person_facepalming: '🤦', person_shrugging: '🤷', dancer: '💃', man_dancing: '🕺',

  // ─── Animals & Nature ────────────────────────────────────────────────────────
  dog: '🐶', cat: '🐱', mouse: '🐭', hamster: '🐹', rabbit: '🐰',
  fox_face: '🦊', bear: '🐻', panda_face: '🐼', koala: '🐨', tiger: '🐯',
  lion: '🦁', cow: '🐮', pig: '🐷', frog: '🐸', monkey: '🐵',
  see_no_evil: '🙈', hear_no_evil: '🙉', speak_no_evil: '🙊',
  gorilla: '🦍', horse: '🐴', unicorn: '🦄', zebra: '🦓', deer: '🦌',
  ox: '🐂', water_buffalo: '🐃', cow2: '🐄', pig2: '🐖', boar: '🐗',
  ram: '🐏', sheep: '🐑', llama: '🦙', goat: '🐐', turkey: '🦃',
  chicken: '🐔', rooster: '🐓', hatching_chick: '🐣', baby_chick: '🐤',
  hatched_chick: '🐥', bird: '🐦', penguin: '🐧', dove: '🕊️', eagle: '🦅',
  duck: '🦆', swan: '🦢', owl: '🦉', flamingo: '🦩', peacock: '🦚',
  parrot: '🦜', snake: '🐍', lizard: '🦎', dragon: '🐉', sauropod: '🦕',
  t_rex: '🦖', whale: '🐳', dolphin: '🐬', seal: '🦭', fish: '🐟',
  tropical_fish: '🐠', blowfish: '🐡', shark: '🦈', octopus: '🐙',
  snail: '🐌', butterfly: '🦋', bug: '🐛', ant: '🐜', bee: '🐝',
  spider: '🕷️', crab: '🦀', lobster: '🦞', shrimp: '🦐', squid: '🦑',
  mushroom: '🍄', shamrock: '☘️', four_leaf_clover: '🍀', seedling: '🌱',
  evergreen_tree: '🌲', deciduous_tree: '🌳', palm_tree: '🌴', cactus: '🌵',
  ear_of_rice: '🌾', herb: '🌿', leaves: '🍃', maple_leaf: '🍂',
  fallen_leaf: '🍂', cherry_blossom: '🌸', blossom: '🌼', sunflower: '🌻',
  bouquet: '💐', rose: '🌹', wilted_flower: '🥀', tulip: '🌷',
  sun_with_face: '🌞', full_moon_with_face: '🌝', crescent_moon: '🌙',
  star: '⭐', star2: '🌟', dizzy: '💫', sparkles: '✨', zap: '⚡',
  fire: '🔥', droplet: '💧', ocean: '🌊', rainbow: '🌈',
  cloud: '☁️', snowflake: '❄️', snowman: '⛄', cyclone: '🌀',
  foggy: '🌁', sunrise: '🌅', sunset: '🌇', night_with_stars: '🌃',

  // ─── Food & Drink ─────────────────────────────────────────────────────────────
  apple: '🍎', green_apple: '🍏', pear: '🍐', tangerine: '🍊', lemon: '🍋',
  banana: '🍌', watermelon: '🍉', grapes: '🍇', strawberry: '🍓',
  melon: '🍈', cherries: '🍒', peach: '🍑', mango: '🥭', pineapple: '🍍',
  coconut: '🥥', kiwi_fruit: '🥝', tomato: '🍅', eggplant: '🍆',
  avocado: '🥑', broccoli: '🥦', leafy_green: '🥬', cucumber: '🥒',
  hot_pepper: '🌶️', corn: '🌽', carrot: '🥕', garlic: '🧄', onion: '🧅',
  potato: '🥔', sweet_potato: '🍠', croissant: '🥐', bagel: '🥯',
  bread: '🍞', baguette_bread: '🥖', pretzel: '🥨', cheese: '🧀',
  egg: '🥚', cooking: '🍳', pancakes: '🥞', waffle: '🧇', bacon: '🥓',
  cut_of_meat: '🥩', poultry_leg: '🍗', meat_on_bone: '🍖', hotdog: '🌭',
  hamburger: '🍔', fries: '🍟', pizza: '🍕', sandwich: '🥪', stuffed_flatbread: '🥙',
  falafel: '🧆', taco: '🌮', burrito: '🌯', salad: '🥗', shallow_pan_of_food: '🥘',
  spaghetti: '🍝', ramen: '🍜', curry: '🍛', rice: '🍚', sushi: '🍣',
  bento: '🍱', dumpling: '🥟', fried_shrimp: '🍤', icecream: '🍦',
  cake: '🎂', birthday: '🎂', cookie: '🍪', doughnut: '🍩', chocolate_bar: '🍫',
  candy: '🍬', lollipop: '🍭', honey_pot: '🍯', coffee: '☕', tea: '🍵',
  milk_glass: '🥛', juice_box: '🧃', cup_with_straw: '🧋', bubble_tea: '🧋',
  beer: '🍺', beers: '🍻', wine_glass: '🍷', champagne: '🍾', cocktail: '🍸',
  tropical_drink: '🍹', bottle_with_popping_cork: '🍾',

  // ─── Activities ───────────────────────────────────────────────────────────────
  soccer: '⚽', basketball: '🏀', football: '🏈', baseball: '⚾',
  softball: '🥎', tennis: '🎾', volleyball: '🏐', rugby_football: '🏉',
  flying_disc: '🥏', '8ball': '🎱', ping_pong: '🏓', badminton: '🏸',
  hockey: '🏒', lacrosse: '🥍', cricket_game: '🏏', golf: '⛳',
  bow_and_arrow: '🏹', fishing_pole_and_fish: '🎣', boxing_glove: '🥊',
  martial_arts_uniform: '🥋', ice_skate: '⛸️', ski: '🎿', sled: '🛷',
  curling_stone: '🥌', dart: '🎯', skateboard: '🛹', surfboard: '🏄',
  trophy: '🏆', medal_sports: '🏅', first_place_medal: '🥇',
  second_place_medal: '🥈', third_place_medal: '🥉', ticket: '🎫',
  tada: '🎉', confetti_ball: '🎊', balloon: '🎈', gift: '🎁',
  christmas_tree: '🎄', fireworks: '🎆', sparkler: '🎇', jack_o_lantern: '🎃',
  game_die: '🎲', chess_pawn: '♟️', spades: '♠️', hearts: '♥️',
  diamonds: '♦️', clubs: '♣️', joker: '🃏', mahjong: '🀄',
  video_game: '🎮', joystick: '🕹️', slot_machine: '🎰', jigsaw: '🧩',

  // ─── Travel & Places ──────────────────────────────────────────────────────────
  car: '🚗', taxi: '🚕', bus: '🚌', trolleybus: '🚎', racing_car: '🏎️',
  police_car: '🚓', ambulance: '🚑', fire_engine: '🚒', minibus: '🚐',
  truck: '🚚', articulated_lorry: '🚛', tractor: '🚜', kick_scooter: '🛴',
  bike: '🚲', motor_scooter: '🛵', motorcycle: '🏍️', train: '🚆',
  train2: '🚋', bullettrain_side: '🚄', bullettrain_front: '🚅',
  steam_locomotive: '🚂', railway_car: '🚃', monorail: '🚝',
  mountain_railway: '🚞', subway: '🚇', light_rail: '🚈', station: '🚉',
  tram: '🚊', bus: '🚌', oncoming_bus: '🚍', trolleybus: '🚎',
  airplane: '✈️', small_airplane: '🛩️', rocket: '🚀', flying_saucer: '🛸',
  helicopter: '🚁', seat: '💺', anchor: '⚓', boat: '⛵', canoe: '🛶',
  speedboat: '🚤', ship: '🚢', ferry: '⛴️', construction: '🚧',
  vertical_traffic_light: '🚦', traffic_light: '🚥',
  house: '🏠', house_with_garden: '🏡', school: '🏫', office: '🏢',
  post_office: '🏣', hospital: '🏥', bank: '🏦', hotel: '🏨',
  convenience_store: '🏪', department_store: '🏬', church: '⛪',
  european_castle: '🏰', japanese_castle: '🏯', stadium: '🏟️',
  mount_fuji: '🗻', camping: '🏕️', beach_umbrella: '🏖️', desert: '🏜️',
  national_park: '🏞️', cityscape: '🏙️', sunrise_over_mountains: '🌄',
  bridge_at_night: '🌉', earth_africa: '🌍', earth_americas: '🌎',
  earth_asia: '🌏', globe_with_meridians: '🌐', world_map: '🗺️',
  japan: '🗾', compass: '🧭',

  // ─── Objects ──────────────────────────────────────────────────────────────────
  watch: '⌚', iphone: '📱', calling: '📲', computer: '💻', keyboard: '⌨️',
  desktop_computer: '🖥️', printer: '🖨️', computer_mouse: '🖱️',
  trackball: '🖲️', minidisc: '💽', floppy_disk: '💾', cd: '💿', dvd: '📀',
  abacus: '🧮', movie_camera: '🎥', film_strip: '🎞️', film_projector: '📽️',
  clapper: '🎬', tv: '📺', camera: '📷', camera_flash: '📸',
  video_camera: '📹', mag: '🔍', mag_right: '🔎', candle: '🕯️', bulb: '💡',
  flashlight: '🔦', money_with_wings: '💸', dollar: '💵', yen: '💴',
  euro: '💶', pound: '💷', moneybag: '💰', credit_card: '💳', gem: '💎',
  wrench: '🔧', hammer: '🔨', nut_and_bolt: '🔩', gear: '⚙️',
  hammer_and_wrench: '🛠️', dagger: '🗡️', sword: '⚔️', shield: '🛡️',
  smoking: '🚬', coffin: '⚰️', urn: '⚱️', amphora: '🏺',
  crystal_ball: '🔮', prayer_beads: '📿', barber: '💈', alembic: '⚗️',
  telescope: '🔭', microscope: '🔬', hole: '🕳️', adhesive_bandage: '🩹',
  pill: '💊', syringe: '💉', drop_of_blood: '🩸', dna: '🧬',
  microbe: '🦠', safety_pin: '🧷', broom: '🧹', basket: '🧺',
  roll_of_paper: '🧻', soap: '🧼', sponge: '🧽', lotion_bottle: '🧴',
  thread: '🧵', yarn: '🧶', shopping: '🛍️', door: '🚪', bed: '🛏️',
  couch_and_lamp: '🛋️', toilet: '🚽', shower: '🚿', bathtub: '🛁',
  scissors: '✂️', card_index_dividers: '🗂️', card_box: '🗃️',
  wastebasket: '🗑️', file_cabinet: '🗄️', notepad_spiral: '🗒️',
  calendar_spiral: '🗓️', clipboard: '📋', pushpin: '📌', round_pushpin: '📍',
  paperclip: '📎', paperclips: '🖇️', straight_ruler: '📏', triangular_ruler: '📐',
  lock: '🔒', unlock: '🔓', lock_with_ink_pen: '🔏', closed_lock_with_key: '🔐',
  key: '🔑', old_key: '🗝️', bell: '🔔', no_bell: '🔕',
  bookmark: '🔖', books: '📚', book: '📖', open_book: '📖',
  newspaper: '📰', newspaper_roll: '🗞️', notebook: '📓', ledger: '📒',
  notebook_with_decorative_cover: '📔', closed_book: '📕', blue_book: '📘',
  orange_book: '📙', green_book: '📗', page_with_curl: '📃',
  scroll: '📜', page_facing_up: '📄', receipt: '🧾', memo: '📝',
  pencil: '✏️', pen: '🖊️', fountain_pen: '🖋️', black_nib: '✒️',
  email: '📧', envelope: '✉️', envelope_with_arrow: '📩',
  incoming_envelope: '📨', e_mail: '📧', inbox_tray: '📥',
  outbox_tray: '📤', package: '📦', label: '🏷️', mailbox: '📫',
  mailbox_closed: '📪', mailbox_with_mail: '📬', mailbox_with_no_mail: '📭',
  postbox: '📮', ballot_box_with_ballot: '🗳️', pencil2: '✏️',
  telephone: '☎️', telephone_receiver: '📞', pager: '📟', fax: '📠',
  battery: '🔋', electric_plug: '🔌', radio: '📻', loudspeaker: '📢',
  mega: '📣', postal_horn: '📯', speaker: '🔈', sound: '🔉', loud_sound: '🔊',

  // ─── Symbols ──────────────────────────────────────────────────────────────────
  heart: '❤️', orange_heart: '🧡', yellow_heart: '💛', green_heart: '💚',
  blue_heart: '💙', purple_heart: '💜', black_heart: '🖤', white_heart: '🤍',
  brown_heart: '🤎', broken_heart: '💔', heavy_heart_exclamation: '❣️',
  two_hearts: '💕', revolving_hearts: '💞', heartbeat: '💓',
  heartpulse: '💗', sparkling_heart: '💖', cupid: '💘', gift_heart: '💝',
  heart_decoration: '💟', peace_symbol: '☮️', cross: '✝️', star_and_crescent: '☪️',
  om: '🕉️', wheel_of_dharma: '☸️', yin_yang: '☯️', orthodox_cross: '☦️',
  star_of_david: '✡️', eight_pointed_black_star: '✴️',
  white_check_mark: '✅', ballot_box_with_check: '☑️', heavy_check_mark: '✔️',
  x: '❌', negative_squared_cross_mark: '❎', heavy_plus_sign: '➕',
  heavy_minus_sign: '➖', heavy_division_sign: '➗',
  curly_loop: '➰', loop: '➿', question: '❓', grey_question: '❔',
  grey_exclamation: '❕', exclamation: '❗', warning: '⚠️',
  zap: '⚡', no_entry: '⛔', no_entry_sign: '🚫', name_badge: '📛',
  prohibited: '🚫', '100': '💯', id: '🆔', information_source: 'ℹ️',
  vs: '🆚', new: '🆕', ng: '🆖', ok: '🆗', up: '🆙', cool: '🆒',
  free: '🆓', zero: '0️⃣', one: '1️⃣', two: '2️⃣', three: '3️⃣',
  four: '4️⃣', five: '5️⃣', six: '6️⃣', seven: '7️⃣', eight: '8️⃣',
  nine: '9️⃣', keycap_ten: '🔟', hash: '#️⃣', asterisk: '*️⃣',
  eject_button: '⏏️', arrow_forward: '▶️', pause_button: '⏸️',
  next_track_button: '⏭️', stop_button: '⏹️', record_button: '⏺️',
  previous_track_button: '⏮️', fast_forward: '⏩', rewind: '⏪',
  twisted_rightwards_arrows: '🔀', repeat: '🔁', repeat_one: '🔂',
  arrow_backward: '◀️', arrow_up_small: '🔼', arrow_down_small: '🔽',
  arrow_double_up: '⏫', arrow_double_down: '⏬', arrow_right: '➡️',
  arrow_left: '⬅️', arrow_up: '⬆️', arrow_down: '⬇️',
  arrow_upper_right: '↗️', arrow_lower_right: '↘️',
  arrow_lower_left: '↙️', arrow_upper_left: '↖️',
  arrow_up_down: '↕️', left_right_arrow: '↔️',
  arrows_counterclockwise: '🔄', arrow_right_hook: '↪️',
  arrow_left_hook: '↩️', arrow_heading_up: '⤴️', arrow_heading_down: '⤵️',
  small_red_triangle: '🔺', small_red_triangle_down: '🔻',
  radio_button: '🔘', large_blue_circle: '🔵', large_orange_circle: '🟠',
  large_yellow_circle: '🟡', large_green_circle: '🟢', large_purple_circle: '🟣',
  large_brown_circle: '🟤', large_red_circle: '🔴', black_circle: '⚫',
  white_circle: '⚪', red_square: '🟥', orange_square: '🟧',
  yellow_square: '🟨', green_square: '🟩', blue_square: '🟦',
  purple_square: '🟪', brown_square: '🟫', black_large_square: '⬛',
  white_large_square: '⬜', black_medium_square: '◼️',
  white_medium_square: '◻️', black_small_square: '▪️',
  white_small_square: '▫️', small_orange_diamond: '🔸',
  small_blue_diamond: '🔹', large_orange_diamond: '🔶',
  large_blue_diamond: '🔷', diamond_shape_with_a_dot_inside: '💠',
  speaker_on: '🔊', muted: '🔇', sos: '🆘', end: '🔚', back: '🔙',
  on: '🔛', soon: '🔜', top: '🔝', recycle: '♻️', fleur_de_lis: '⚜️',
  trident: '🔱', beginner: '🔰', heavy_dollar_sign: '💲',
  copyright: '©️', registered: '®️', tm: '™️',
  wavy_dash: '〰️', part_alternation_mark: '〽️',
  clock1: '🕐', clock2: '🕑', clock3: '🕒', clock4: '🕓',
  clock5: '🕔', clock6: '🕕', clock7: '🕖', clock8: '🕗',
  clock9: '🕘', clock10: '🕙', clock11: '🕚', clock12: '🕛',
  alarm_clock: '⏰', stopwatch: '⏱️', timer_clock: '⏲️', hourglass: '⌛',
  hourglass_flowing_sand: '⏳', calendar: '📅', date: '📅',

  // ─── Flags ────────────────────────────────────────────────────────────────────
  checkered_flag: '🏁', triangular_flag_on_post: '🚩', crossed_flags: '🎌',
  black_flag: '🏴', white_flag: '🏳️', rainbow_flag: '🏳️‍🌈',
  pirate_flag: '🏴‍☠️',

  // ─── GitHub-specific ─────────────────────────────────────────────────────────
  octocat: '🐙', shipit: '🚢', squirrel: '🐿️', basecamp: '🏕️',
  feelsgood: '👍', finnadie: '😱', goberserk: '😤', godmode: '🔱',
  hurtrealbad: '😭', rage1: '😡', rage2: '😡', rage3: '😡', rage4: '😡',
  suspect: '🤔', trollface: '😈',
}
